USE [master]
GO
/****** Object:  Database [boostlingo-db]    Script Date: 6/14/2024 1:04:30 PM ******/
CREATE DATABASE [boostlingo-db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'boostlingo-db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\boostlingo-db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'boostlingo-db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\boostlingo-db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [boostlingo-db] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [boostlingo-db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [boostlingo-db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [boostlingo-db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [boostlingo-db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [boostlingo-db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [boostlingo-db] SET ARITHABORT OFF 
GO
ALTER DATABASE [boostlingo-db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [boostlingo-db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [boostlingo-db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [boostlingo-db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [boostlingo-db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [boostlingo-db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [boostlingo-db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [boostlingo-db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [boostlingo-db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [boostlingo-db] SET  DISABLE_BROKER 
GO
ALTER DATABASE [boostlingo-db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [boostlingo-db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [boostlingo-db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [boostlingo-db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [boostlingo-db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [boostlingo-db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [boostlingo-db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [boostlingo-db] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [boostlingo-db] SET  MULTI_USER 
GO
ALTER DATABASE [boostlingo-db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [boostlingo-db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [boostlingo-db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [boostlingo-db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [boostlingo-db] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [boostlingo-db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [boostlingo-db] SET QUERY_STORE = ON
GO
ALTER DATABASE [boostlingo-db] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [boostlingo-db]
GO
/****** Object:  Table [dbo].[User]    Script Date: 6/14/2024 1:04:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[id] [varchar](50) NOT NULL,
	[name] [varchar](200) NOT NULL,
	[language] [varchar](50) NOT NULL,
	[bio] [varchar](max) NULL,
	[version] [decimal](18, 2) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [boostlingo-db] SET  READ_WRITE 
GO
